include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_null_checks: true

analyzer:
  errors:
    dead_null_aware_expression: error
    deprecated_member_use: warning
    prefer_final_fields: info
